# Generated by Django 4.2.5 on 2023-09-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_usr_newdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdata',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
