# Generated by Django 4.2.5 on 2023-09-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_newdata_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newdata',
            name='is_delete',
        ),
    ]
